services:
  db:
    container_name: db
    image: postgres:16
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - engineer

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 14140:80
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - engineer

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: data_volume
      o: bind

networks:
  engineer:
    driver: bridge